service:
  name: jukebot-backend

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    STAGE: ${opt:stage}

functions:
  index:
    handler: index.index
    events:
      - http:
          method: get
          path: /
